// In this code we are going to find all the SUBSEQUENCES of a string using recursion

// Given a string, we have to find out all its subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.

// Input : abc
// Output : a, b, c, ab, bc, ac, abc.

#include<iostream>
#include<string>
#include<vector>

using namespace std;

auto subsequences(string str,int i,string s,vector<string> *result){
    if(i==str.size()){
        result->push_back(s);
        return 0;
    }
    subsequences(str,i+1,s+str[i],result);
    subsequences(str,i+1,s,result);
}

int main(){
    string s;
    cout << "Enter the String : ";
    cin >> s;

    vector<string> result;

    subsequences(s,0,"",&result);

    for(int i=0;i<result.size();i++){
        cout << result[i] << " " ;
    }
    return 0;
}